#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_FFI_FFI_H 1
#define USE_HEADER_HACKS 1
#define HAVE_FFI_CLOSURE_ALLOC 1
#define HAVE_FFI_PREP_CIF_VAR 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_DLFCN_H 1
#define HAVE_DLOPEN 1
#define HAVE_DLCLOSE 1
#define HAVE_DLSYM 1
#define HAVE_DLERROR 1
#define SIGNEDNESS_OF_SIZE_T +1
#endif
