#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_CONFIG_H 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_SHA1_TRANSFORM 1
#define HAVE_TYPE_SHA_CTX 1
#define SHA1_USE_OPENSSL 1
#define HAVE_SYS_CDEFS_H 1
#endif
