#ifndef EXTCONF_H
#define EXTCONF_H
#define RUBY_BIGDECIMAL_VERSION "2.0.0"
#define HAVE_LABS 1
#define HAVE_LLABS 1
#define HAVE_FINITE 1
#define HAVE_RB_RATIONAL_NUM 1
#define HAVE_RB_RATIONAL_DEN 1
#define HAVE_RB_ARRAY_CONST_PTR 1
#define HAVE_RB_SYM2STR 1
#define HAVE_RB_OPTS_EXCEPTION_P 1
#endif
