#ifndef EXTCONF_H
#define EXTCONF_H
#define NDEBUG 1
#define HAVE_CONFIG_H 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_RIPEMD160_TRANSFORM 1
#define HAVE_TYPE_RIPEMD160_CTX 1
#define RMD160_USE_OPENSSL 1
#define HAVE_SYS_CDEFS_H 1
#endif
