#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_CONFIG_H 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_MD5_TRANSFORM 1
#define HAVE_TYPE_MD5_CTX 1
#define MD5_USE_OPENSSL 1
#define HAVE_SYS_CDEFS_H 1
#endif
